/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blockchainassignment;

import blockchain.Blockchain;
import static blockchainassignment.ViewTransactionPage.username;
import crypto.Symmetric;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Date;
import java.util.List;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;

/**
 *
 * @author Acer
 */
public class Ledger extends javax.swing.JFrame {

    /**
     * Creates new form Ledger
     */
    public Ledger() {
        initComponents();
        
        String allTransaction = "";
        String[] splitArray;
        Blockchain bc = Blockchain.getInstance("master/chain.bin");
        
        int lastIndex = bc.get().getLast().getBlockHeader().getIndex();
        
        for(int i = 0; i <= lastIndex; i++){
            String index = String.valueOf(i);
            String currentHash = bc.get().get(i).getBlockHeader().getCurrentHash();
            String previousHash = bc.get().get(i).getBlockHeader().getPreviousHash();
            long datetime = bc.get().get(i).getBlockHeader().getTimeStamp();
            Date date = new Date(datetime);
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String formattedDateTime = dateFormat.format(date);
            if(i != 0){
                String transaction = bc.get().get(i).getTranx().getTranxLst().get(0);
                splitArray = transaction.split(" , ");
                if(splitArray.length == 11){
                    allTransaction += "Index: " + index + "\nCurrent Hash: " + currentHash + "\nPrevious Hash: " + previousHash + "\nTransaction Time: " + formattedDateTime + "\nOrder ID: " + splitArray[1] + "\nSender: " + splitArray[0] + "\nSender Address: " + splitArray[2] + "\nRecipient Address: " + splitArray[3] + "\nParcel Dimension: " + splitArray[4] + "\nWeight: " + splitArray[5] + "\nFragility: " + splitArray[6] + "\nDescription: " + splitArray[7] + "\nPayment Method: " + splitArray[8] + "\nPayment Amount: " + splitArray[9] + "\nDeliveryman: " + splitArray[10] + "\n\n";
                }
                if(splitArray.length == 3){
                    allTransaction += "Index: " + index + "\nCurrent Hash: " + currentHash + "\nPrevious Hash: " + previousHash + "\nTransaction Time: " + formattedDateTime + "\nOrder ID: " + splitArray[0] + "\nVehicle Plate: " + splitArray[1] + "\nCurrent Location: " + splitArray[2] + "\n\n";
                }
            }else{
                allTransaction += "Index: " + index + "\nCurrent Hash: " + currentHash + "\nPrevious Hash: " + previousHash + "\nTransaction Time: " + formattedDateTime +"\n\n";
            }
            txtAreaLedger.setText(allTransaction);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaLedger = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        jLabel1.setText("View Ledger");

        txtAreaLedger.setEditable(false);
        txtAreaLedger.setColumns(20);
        txtAreaLedger.setRows(5);
        jScrollPane1.setViewportView(txtAreaLedger);

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ledger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ledger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ledger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ledger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ledger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaLedger;
    // End of variables declaration//GEN-END:variables
}
