/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blockchainassignment;

import blockchain.Blockchain;
import crypto.Symmetric;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Date;
import java.util.List;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import org.apache.commons.codec.DecoderException;

/**
 *
 * @author Acer
 */
public class ViewTransactionPage extends javax.swing.JFrame {

    public static String username;
    /**
     * Creates new form ViewTransactionPage
     */
    public ViewTransactionPage(String name) {
        initComponents();
        username = name;
        Blockchain bc = Blockchain.getInstance("master/chain.bin");

        List<String> indexLst = new ArrayList();
        List<String> publicKeyLst = new ArrayList();
        try{
            BufferedReader myfile = new BufferedReader(new FileReader("BlockIndex.txt"));
            String [] lineArr;
            String line;
            while((line = myfile.readLine())!=null){
                lineArr = line.split(" , ");
                if((lineArr.length == 4) && lineArr[0].equals(username)){
                    indexLst.add(lineArr[1]);
                    publicKeyLst.add(lineArr[2]);
                }
                if((lineArr.length == 7) && lineArr[0].equals(username)){
                    indexLst.add(lineArr[1]);
                    publicKeyLst.add(lineArr[3]);
                }
            }
        }
        catch(IOException e){
            e.printStackTrace();
        }
        
        String allTransaction = "";
        String [] splitArray;
        int cnt = 0;
        Symmetric symm = new Symmetric();
        try{
            for(String index: indexLst){
                String publicKeyString = publicKeyLst.get(cnt);
                byte[] decodedKey = Base64.getDecoder().decode(publicKeyString);
                SecretKey originalKey = new SecretKeySpec(decodedKey, 0, decodedKey.length, "AES");
                long datetime = bc.get().get(Integer.parseInt(index)).getBlockHeader().getTimeStamp();
                Date date = new Date(datetime);
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                String formattedDateTime = dateFormat.format(date);
                String transaction = bc.get().get(Integer.parseInt(index)).getTranx().getTranxLst().get(0);
                splitArray = transaction.split(" , ");
                if(splitArray.length == 11){
                    allTransaction += "Transaction Time: " + formattedDateTime + "\nOrder ID: " + splitArray[1] + "\nSender Address: " + symm.decrypt(splitArray[2], originalKey) + 
                            "\nRecipient Address: " + symm.decrypt(splitArray[3], originalKey) + "\nParcel Dimension: " + splitArray[4] + "\nWeight: " + splitArray[5] + "\nFragility: " + 
                            splitArray[6] + "\nDescription: " + splitArray[7] + "\nPayment Method: " + symm.decrypt(splitArray[8], originalKey) + "\nPayment Amount: " + 
                            symm.decrypt(splitArray[9], originalKey) + "\nDeliveryman: " + splitArray[10] + "\n\n";
                }
                if(splitArray.length == 3){
                    allTransaction += "Transaction Time: " + formattedDateTime + "\nOrder ID: " + splitArray[0] + "\nVehicle Plate: " + splitArray[1] + "\nCurrent Location: " + splitArray[2] + "\n\n";
                }      
                cnt++;
            }
            txtAreaDisplay.setText(allTransaction);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public ViewTransactionPage(){}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDisplay = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        lblTitle.setText("View Transaction Page");

        txtAreaDisplay.setEditable(false);
        txtAreaDisplay.setColumns(20);
        txtAreaDisplay.setRows(5);
        jScrollPane1.setViewportView(txtAreaDisplay);

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTransactionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTransactionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTransactionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTransactionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTransactionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtAreaDisplay;
    // End of variables declaration//GEN-END:variables
}
